import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  FastForward,
  File,
  FileText,
  GalleryVertical,
  HelpCircle,
  Image,
  Laptop,
  Layers,
  Lightbulb,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  BaggageClaim,
  Settings,
  ShieldCheck,
  Shuffle,
  SunMedium,
  Trash,
  User,
  X,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: BaggageClaim,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  check: Check,
  fastForward: FastForward,
  galleryVertical: GalleryVertical,
  layers: Layers,
  lightbulb: Lightbulb,
  shuffle: Shuffle,
  shieldCheck: ShieldCheck,
};
